### ISSUE TITLE
`fbp` queue messages seems to endlessly accumulate?

### ISSUE THREAD

**Issue by Jaspooky** [msgflo/msgflo#190]
![image](https://user-images.githubusercontent.com/12173515/118371387-59282800-b5a4-11eb-99a1-baf171a20e05.png)

```json
{
  "protocol": "discovery",
  "command": "participant",
  "payload": {
    "component": "Console",
    "icon": "file-word-o",
    "label": "Prints to console",
    "inports": [
      { "id": "in", "type": "any", "hidden": false, "queue": "log.IN" }
    ],
    "outports": [],
    "role": "log",
    "id": "log-b697265e-a38f-46f9-95d6-10291322d08a"
  }
}
```

It appears to fire every few seconds? Is there something I'm missing to consume these? The setup is working, it runs the behaviours I expect

**Comment by jonnor** [comment]
This is because on AMQP the FBP discovery messages is sent to a queue, instead of just an exchange which consumers can bind to. The is tracked here, https://github.com/msgflo/msgflo/issues/13 - closing in favor of that one, feel free to comment more there

The workaround for now would be to periodically drain the fbp queue

**Comment by jonnor** [comment]
Another workaround is to run the msgflo coordinator, then it will eat those messages
